spring:
  datasource:
    name: test  #数据库名
    #url: jdbc:mysql://121.5.200.64:3306/test #url
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=false #url
    username: root  #用户名
    #password: wu123456  #密码
    password: h%ato-K1sjLd  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
      mapper-locations: classpath*:/mapper/*.xml  #配置映射文件
      type-aliases-package: com.example.whdemo.bean #配置实体类